spring:
  application:
    name: JBT-BE

  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}


jwt:
  secret: ${JWT_SECRET}
