spring:
  application:
    name: JBT-BE

  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jackson:
    property-naming-strategy: SNAKE_CASE


jwt:
  secret: ${JWT_SECRET}

aws:
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket-name: ${S3_BUCKET}
    region: ${S3_REGION}
    file-name-prefix: ${S3_PREFIX}
    bucket-url: ${S3_BUCKET_URL}
